server.port=8080

# Se você não tem a variável MONGO_URI no Windows, declare ela aqui:
MONGO_URI=mongodb+srv://allangabrielcontato_db_user:uUR3EAHUUJ6vsulV@cluster1.eflnpnq.mongodb.net/ergane?appName=Cluster1
# O Ergane precisa do JWT (o Gamelibrary não precisava)
security.jwt.secret=AteQueAErganeAjudaAResolverVariosProblemasFinanCEIROS
security.jwt.expiration-minutes=1440