# Porta do servidor (padrão é 8080, mas você pode mudar se quiser)
server.port=

# Conexão REAL com o MongoDB Atlas (Substitua pelos seus dados)
spring.data.mongodb.uri=

# Segredo para gerar o Token JWT (Invente uma frase bem longa e complexa)
jwt.secret=